"""initial models

Revision ID: 6d37d1589ea0
Revises: 
Create Date: 2026-10-02 00:40:40.484418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d37d1589ea0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_bot',
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('perfil',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.CheckConstraint("nome IN ('ADMIN', 'ATENDENTE')", name='ck_perfil_nome'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('perfil_id', sa.SmallInteger(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('atendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone_solicitante', sa.String(length=20), nullable=False),
    sa.Column('usuario_atendente_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ABERTO', 'EM_ATENDIMENTO', 'FECHADO')", name='ck_atendimento_status'),
    sa.ForeignKeyConstraint(['usuario_atendente_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conteudo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('fonte', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('tabela_afetada', sa.String(length=100), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('remetente', sa.String(length=12), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("remetente IN ('USUARIO', 'BOT', 'ATENDENTE')", name='ck_mensagem_remetente'),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('no_fluxo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=24), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('conteudo_id', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.SmallInteger(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("(tipo = 'RESPOSTA' AND conteudo_id IS NOT NULL) OR (tipo <> 'RESPOSTA')", name='ck_no_fluxo_conteudo'),
    sa.CheckConstraint("tipo IN ('MENU', 'RESPOSTA', 'ATENDENTE')", name='ck_no_fluxo_tipo'),
    sa.CheckConstraint('length(titulo) <= 24', name='ck_no_fluxo_titulo'),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudo.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['no_fluxo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_fluxo_id', sa.Integer(), nullable=False),
    sa.Column('util', sa.Boolean(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['no_fluxo_id'], ['no_fluxo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    perfil = sa.table(
        "perfil",
        sa.column("id", sa.SmallInteger),
        sa.column("nome", sa.String),
    )
    op.bulk_insert(
        perfil,
        [
            {"id": 1, "nome": "ADMIN"},
            {"id": 2, "nome": "ATENDENTE"},
        ],
    )

    config_bot = sa.table(
        "config_bot",
        sa.column("chave", sa.String),
        sa.column("valor", sa.String),
    )
    op.bulk_insert(
        config_bot,
        [
            {
                "chave": "boas_vindas",
                "valor": "Olá! Sou o assistente da Biblioteca. Escolha uma opção:",
            },
            {
                "chave": "fallback",
                "valor": "Não entendi. Vou te mostrar o menu novamente.",
            },
            {"chave": "menu_botao", "valor": "Ver opções"},
            {
                "chave": "atendente_msg",
                "valor": "Certo! Encaminhei seu caso para um atendente. Aguarde, por favor.",
            },
            {"chave": "feedback_pergunta", "valor": "Essa resposta te ajudou?"},
            {"chave": "feedback_obrigado", "valor": "Obrigado pelo seu feedback!"},
            {"chave": "feedback_sim", "valor": "Ajudou"},
            {"chave": "feedback_nao", "valor": "Não ajudou"},
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('no_fluxo')
    op.drop_table('mensagem')
    op.drop_table('log')
    op.drop_table('conteudo')
    op.drop_table('atendimento')
    op.drop_table('usuario')
    op.drop_table('perfil')
    op.drop_table('config_bot')
    op.drop_table('categoria')
    # ### end Alembic commands ###
